name: Backend CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      -main
    path:
      - 'starter/backend/**'

env:
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
  ECR_REPOSITORY: backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  Lint:
    runs-on: ubuntu-latest
    environment: Development Environment
    steps:
      - name: Checkout re[p]
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install flake8
        working-directory: starter/backend

      - name: Run linting
        run: flake8 . 
        working-directory: starter/backend

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python 3.8 
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install pipenv
        working-directory: starter/backend

      - name: Install project dependencies
        run: pipenv install --dev
        working-directory: starter/backend

      - name: Run tests
        run: pipenv run pytest 
        working-directory: starter/backend

  Build:
    runs-on: ubuntu-latest
    needs: [Lint, Test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker build environment
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG backend/
        working-directory: backend

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker image to Amazon ECR
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  # Push the image to ECR

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name your-cluster-name --region ${{ secrets.AWS_REGION }}

      - name: Deploy to Kubernetes
        run: |
          cd starter/backend/k8s
          kustomize edit set image backend=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  # Update the image in Kubernetes manifests
          kustomize build | kubectl apply -f -  # Apply the changes to the Kubernetes cluster
