name: Backend CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'starter/backend/**'

jobs:
  Lint:
    runs-on: ubuntu-latest
    environment: Development Environment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install flake8
        working-directory: starter/backend

      - name: Run linting
        run: flake8 . 
        working-directory: starter/backend

  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Set up Python 3.8 
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install pipenv
        working-directory: starter/backend

      - name: Install project dependencies
        run: pipenv install --dev
        working-directory: starter/backend

      - name: Run tests
        run: pipenv run pytest 
        working-directory: starter/backend

  Build:
    runs-on: ubuntu-latest
    needs: [Lint, Test]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker build environment
        run: |
          docker build --tag 458978242428.dkr.ecr.us-east-1.amazonaws.com/backend:latest .
        working-directory: starter/backend

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 458978242428.dkr.ecr.us-east-1.amazonaws.com/backend:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name cluster --region us-east-1

      - name: Deploy to Kubernetes
        run: |
          cd starter/backend/k8s
          kustomize edit set image backend=458978242428.dkr.ecr.us-east-1.amazonaws.com/backend:latest
          kustomize build | kubectl apply -f -

      - name: Print Application URLs
        run: kubectl get svc -A