name: Backend CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    path:
      - 'starter/backend/**'

jobs:
  Lint:
    runs-on: ubuntu-latest
    environment: Development Environment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        working-directory: starter/backend
        run:  |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8
      - name: Run Lint
        run: cd starter/backend && pipenv run lint
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install Dependencies
        working-directory: starter/backend 
        run:  |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install flake8

      - name: Test
        run: cd starter/backend && pipenv install pytest && pipenv run test

  Build:
    needs: [Lint, Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          cd starter/backend
          docker build --tag mp-backend:latest .